name: casual-challenge-local
services:
  casual_challenge_application:
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - "8080:8080"
    container_name: casual-challenge-app-local
    depends_on:
      postgresql_db:
        condition: service_healthy
    volumes:
      - ./src/main/resources/static:/opt/app/static:ro
      - ./src/main/resources/templates:/opt/app/templates:ro
      - seasons:/opt/app/seasons
  postgresql_db:
    image: "postgres:17-alpine"
    ports:
      - "127.0.0.1:5433:5432"
    container_name: casual-challenge-db-local
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: casual_challenge
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d casual_challenge"]
      interval: 5s
      timeout: 5s
      retries: 20
volumes:
  db_data:
  seasons:
