spring:
  application:
    name: casual-challenge-application
  config:
    import: optional:configtree:/run/secrets/
  datasource:
    url: jdbc:postgresql://localhost:5432/casual_challenge?stringtype=unspecified
    username: postgres
    password: postgres
  jpa:
    show-sql: true
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
server:
  compression:
    enabled: true # enable compression for requests with Accept-Encoding: gzip
springdoc:
  disable-i18n: true
  show-spring-cloud-functions: false
  swagger-ui:
    disable-swagger-default-url: true
    path: /docs
casual-challenge:
  security:
    jwt:
      secret-key: ${jwt_private_key}
    rate-limit:
      capacity: 8
      refill-per-minute: 2



---
server:
  port: 8443
  ssl:
    enabled: true
    key-store: /etc/ssl/certs/ssl/cloudflare-origin.p12
    key-store-password: ${key_store_password}
    key-store-type: PKCS12
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://postgresql_db:5432/casual_challenge?stringtype=unspecified
    password: ${postgres_password}
