spring:
  application:
    name: casual-challenge-application
  config:
    import: optional:configtree:/run/secrets/
  datasource:
    url: jdbc:postgresql://localhost:5432/casual_challenge
    username: postgres
    password: postgres
  jpa:
    show-sql: true
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
springdoc:
  disable-i18n: true
  show-spring-cloud-functions: false
  swagger-ui:
    disable-swagger-default-url: true
    path: /docs
casual-challenge:
  security:
    jwt:
      secret-key: ${jwt_private_key}
    rate-limit:
      capacity: 2
      refill-per-minute: 1



---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://postgresql_db:5432/casual_challenge
    password: ${postgres_password}
