name: CI/CD
on:
  workflow_dispatch:
#  push:
#    branches:
#      - master
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd ${{ secrets.PROJECT_PATH }} # /home/wormies/wormies
            git pull origin master
            ./gradlew clean build
            docker compose up --build -d --remove-orphans
            docker image prune -a -f
